services:
  # --- INFRASTRUKTURA ---
  timescale:
    image: timescale/timescaledb:latest-pg18
    container_name: timescale_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # --- INGESTERY ---
  raw-ingester:
    build:
      context: .
      args:
        - MODULE_PATH=cmd/raw-input
    environment:
      - MQTT_CLIENT_ID=raw-ingester
      - MQTT_URL=${MQTT_BROKER_URL}
      - RAW_LISTEN_PORT=6000
      - SECRET_KEY=${SECRET_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - "6000:6000"
    depends_on:
      - mosquitto

  mqtt-ingester:
    build:
      context: .
      args:
        - MODULE_PATH=cmd/mqtt-input
    environment:
      - MQTT_URL=${MQTT_BROKER_URL}
      - MQTT_CLIENT_ID=mqtt-inputer
      - SOURCE_MQTT_URL=${SOURCE_MQTT_URL}
      - SOURCE_MQTT_CLIENT_ID=mqtt-inputer-input
      - SOURCE_TOPIC=${SOURCE_MQTT_TOPIC}
      - SECRET_KEY=${SECRET_KEY}

  weather-ingester:
    build:
      context: .
      args:
        - MODULE_PATH=cmd/openmeteo-input
    environment:
      - MQTT_CLIENT_ID=weather-ingester-docker
      - MQTT_URL=${MQTT_BROKER_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mosquitto

  # --- PARSERY ---
  iot-parser:
    build:
      context: .
      args:
        - MODULE_PATH=cmd/iot-parser
    environment:
      - MQTT_CLIENT_ID=iot-parser-docker
      - MQTT_URL=${MQTT_BROKER_URL}
      - SECRET_KEY=${SECRET_KEY}
      - mosquitto

  web-parser:
    build:
      context: .
      args:
        - MODULE_PATH=cmd/web-parser
    environment:
      - MQTT_CLIENT_ID=web-parser-docker
      - MQTT_URL=${MQTT_BROKER_URL}
      - SECRET_KEY=${SECRET_KEY}
      - mosquitto

  # --- STORAGE ---
  storager:
    build:
      context: .
      args:
        - MODULE_PATH=cmd/storager
    environment:
      - MQTT_URL=${MQTT_BROKER_URL}
      - DB_HOST=timescale
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - STORAGE_TYPE=timescaledb
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      timescale:
        condition: service_healthy
      mosquitto:
        condition: service_started
