component_name: "owm-prague"
environment: "development"
log_level: "info"
secret_key: "moje-velmi-bezpecne-heslo-ktere-nikdo-neuhadne"

mqtt:
  broker_url: "tcp://localhost:1883"
  client_id: "owm-ingester-v1"

api_key: "" # Tady vlož svůj klíč
lat: 50.0755
lon: 14.4378
interval_minutes: 10
